version: '2.3'

services:
  gitserver:
    image: ${DOCKER_USERNAME}/oufti-gitserver
    restart: unless-stopped
    ports:
    - "3000:3000"
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}

  jenkins:
    image: ${DOCKER_USERNAME}/oufti-jenkins
    restart: unless-stopped
    ports:
    - "8080:8080"
    environment:
    - JENKINS_EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}
    - JAVA_OPTS=-XshowSettings:vm -Djenkins.install.runSetupWizard=false -Xms256m -Xmx512m

  jenkins-docker-node:
    image: ${DOCKER_USERNAME}/oufti-jenkins-docker-node
    restart: unless-stopped
    privileged: true
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
